# -*- coding: utf-8 -*-
#"""
#Created on Thu Sep 21 15:09:14 2017
#
#@author: Colin Brosseau
#"""

EEV400x1340B:  # Liquid nitrogen cooled detector
    setpoint_temperature: -100  # celcius
    speed: 0
    gain: 1
    exposureTime: 1  # second

EEV256x1024BR:  # Pixis 256
    setpoint_temperature: -70  # celcius
    speed: 0
    gain: 1
    exposureTime: 1  # second
    shutter: 
        reverse: False
        delay: 0.1  # second
